### ISSUE TITLE
btSerial.close();

### ISSUE THREAD

**Issue by daksen** [eelcocramer/node-bluetooth-serial-port#200]
Error: usage: close(address)
    at BluetoothSerialPort.close (C:\Users\DakSen\Documents\Workspace\NETICA\netibot\bluetooth\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:127:29)
    at getDisconnection (C:\Users\DakSen\Documents\Workspace\NETICA\netibot\bluetooth\bluetooth.js:91:12)
    at Socket.<anonymous> (C:\Users\DakSen\Documents\Workspace\NETICA\netibot\bluetooth\bluetooth.js:32:3)
    at Socket.emit (events.js:182:13)
    at C:\Users\DakSen\Documents\Workspace\NETICA\netibot\bluetooth\node_modules\socket.io\lib\socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
C:\Users\DakSen\Documents\Workspace\NETICA\netibot\bluetooth\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:127
            this.connection.close();
                            ^

Error: usage: close(address)
    at BluetoothSerialPort.close (C:\Users\DakSen\Documents\Workspace\NETICA\netibot\bluetooth\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:127:29)
    at BluetoothSerialPort.dataListener (C:\Users\DakSen\Documents\Workspace\NETICA\netibot\bluetooth\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:90:30)
    at BluetoothSerialPort.emit (events.js:182:13)
    at C:\Users\DakSen\Documents\Workspace\NETICA\netibot\bluetooth\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:76:38

**Comment by daksen** [comment]
in 2.1.7 it works

**Comment by eelcocramer** [comment]
Thanks. I will look into it. @asdo6rs any idea?

**Comment by asdo6rs** [comment]
@eelcocramer, yes, this was a mistaken change in my PR.  I only meant to change BluetoothSerialPortServer and the changes on lines 108 and 127 of bluetooth-serial-port.js were to BluetoothSerialPort.  Those two changes should be reverted so that address is passed to close().  I tried creating a branch in your repo to make the fix, but I don't have rights to do a push.  I wouldn't be able to create a PR from my forked version until early next week.  If you want to fix it now, you can make the two changes I referenced above.  Otherwise, I can have a PR to you from my forked copy sometime on Tuesday (US time).

**Comment by eelcocramer** [comment]
Just released version 2.2.1 that should fix this regression. I will merge the fix into master as soon tests are done.

Thanks @asdo6rs for the quick response and @daksen for reporting.

**Comment by iamsush** [comment]
The issue is still persistent. I am getting the same error in the latest build (v2.2.2). Please help.

**Comment by eelcocramer** [comment]
@iamsush 2.1.7 also works for you? If so, can you please provide some more information. What OS are you using, can you share a stack trace?

**Comment by iamsush** [comment]
@eelcocramer yes, 2.1.7 is working for me.
Issue has occured in Ubuntu 16.04 as well as windows 10 both in version 2.2.2 .
Here is the stack trace :
```
Error: usage: close(address)
    at BluetoothSerialPort.close (C:\Users\Pankaj\Desktop\Sushant-delete\demoWorkspace\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:127:29)
    at closePort (C:\Users\Pankaj\Desktop\Sushant-delete\demoWorkspace\app.js:95:22)
    at Interface.rl.on (C:\Users\Pankaj\Desktop\Sushant-delete\demoWorkspace\app.js:24:13)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._line (readline.js:638:8)
    at Interface._ttyWrite (readline.js:919:14)
    at ReadStream.onkeypress (readline.js:168:10)
    at ReadStream.emit (events.js:182:13)
    at emitKeys (internal/readline.js:424:14)

C:\Users\Pankaj\Desktop\Sushant-delete\demoWorkspace\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:127
            this.connection.close();
                            ^

Error: usage: close(address)
    at BluetoothSerialPort.close (C:\Users\Pankaj\Desktop\Sushant-delete\demoWorkspace\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:127:29)
    at BluetoothSerialPort.dataListener (C:\Users\Pankaj\Desktop\Sushant-delete\demoWorkspace\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:90:30)
    at BluetoothSerialPort.emit (events.js:187:15)
    at C:\Users\Pankaj\Desktop\Sushant-delete\demoWorkspace\node_modules\bluetooth-serial-port\lib\bluetooth-serial-port.js:76:38
```

**Comment by iamsush** [comment]
I have used the following demo Program to test it. Might be helpful for others.

```
const readline = require('readline');
var btSerial = new (require('bluetooth-serial-port')).BluetoothSerialPort();

var bluetoothPortList = [];

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.on('line', (input) => {
    switch (input) {
        case 'inquire': {
            inquire();
            break;
        }
        case 'connect': {
            rl.question('Which device to connect? ', (answer) => {
                connect(bluetoothPortList[answer].address);
            });
            break;
        }
        case 'close': {
            closePort();
            break;
        }
        case 'clear': {
            clear();
            break;
        }
        default: {
            console.log(`Received: ${input}`);
            break;
        }
    }
});

btSerial.on('data', buffer => {
    console.log(buffer.toString('utf-8'));
});

btSerial.on('closed', () => {
    console.log('Bluetooth disconnected');
});

btSerial.on('failure', err => {
    console.log(err);
});

btSerial.on('found', (address, name) => {
    console.log(`${address} = ${name}`);
        bluetoothPortList.push({
            address,
            name
        });
});

btSerial.on('finished', () => {
    console.log('finished');
});

const inquire = () => {
    btSerial.inquire();
};

const clear = () => {
    bluetoothPortList = [];
}

const connect = address => {
    console.log(address);
    btSerial.findSerialPortChannel(address, channel => {
        btSerial.connect(address, channel, () => {
            console.log('connected');
        }, () => {
            console.log('cannot connect');
        });
    }, err => {
        console.log(err);
    });
};

const closePort = () => {
    if (btSerial.isOpen()) {
        try {
            btSerial.close();
        } catch (err) {
            console.log(err);
        }
    }
};
```

**Comment by eelcocramer** [comment]
Weird, it was fixed before but there it is again. Will fix this soon.

**Comment by iamsush** [comment]
Also, there is one more issue regarding closing the port.

When we close the port, I guess some listeners remain open and bluetooth-serial-port does not close it. I have some issue because of that too. (I am not able to read data If I try to connect the port after first time, it has some ambiguous behaviour).

** listeners remain open**
```
Which device to connect? 2
00:21:13:03:C8:1B
connected
close
Bluetooth disconnected

Bluetooth disconnected
Bluetooth disconnected
connect
Which device to connect? 2
00:21:13:03:C8:1B
connected
close
Bluetooth disconnected

Bluetooth disconnected
Bluetooth disconnected
Bluetooth disconnected
connect
Which device to connect? 2
00:21:13:03:C8:1B
cloconnected
> close
Bluetooth disconnected

Bluetooth disconnected
Bluetooth disconnected
Bluetooth disconnected
Bluetooth disconnected
```

**Comment by eelcocramer** [comment]
Can you please check that in the new (2.2.3) version once I fixed and publish the patch for this issue? 

If the issue still persist can you please open up a new issue for your finding? That will keep the discussion clean and on-topic. Thanks!

**Comment by iamsush** [comment]
Ok sure, I'll do that.
When can we expect the new release of the new version? Thanks.

**Comment by eelcocramer** [comment]
It was released just now.

**Comment by iamsush** [comment]
Right now, it is working good with the _close()_ function. But I am still having some issue which I already mentioned above, about reading the data from the connection. I have created a new issue for that [#210](https://github.com/eelcocramer/node-bluetooth-serial-port/issues/210).

Thanks.
